/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Metrics
     * @description Prometheus-style metrics endpoint summarising jobs and snapshots.
     */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Issue Report
     * @description Accept a public issue report submission.
     *
     *     This endpoint intentionally collects minimal data and does not accept
     *     attachments. Reports are meant for metadata errors, broken snapshots,
     *     missing coverage, or takedown requests.
     */
    post: operations["submit_issue_report_api_reports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Usage Metrics
     * @description Return aggregated usage metrics (daily counts).
     */
    get: operations["get_usage_metrics_api_usage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Exports Manifest
     * @description Describe the public export endpoints and limits.
     */
    get: operations["get_exports_manifest_api_exports_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exports/snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export Snapshots
     * @description Stream snapshot metadata exports in JSONL or CSV format.
     */
    get: operations["export_snapshots_api_exports_snapshots_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Export Snapshots Head
     * @description Return headers for snapshot exports without streaming a body.
     *
     *     Some clients use HEAD requests (`curl -I`) to inspect download headers.
     */
    head: operations["export_snapshots_head_api_exports_snapshots_head"];
    patch?: never;
    trace?: never;
  };
  "/api/exports/changes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export Changes
     * @description Stream change event exports in JSONL or CSV format.
     */
    get: operations["export_changes_api_exports_changes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Export Changes Head
     * @description Return headers for change exports without streaming a body.
     *
     *     Some clients use HEAD requests (`curl -I`) to inspect download headers.
     */
    head: operations["export_changes_head_api_exports_changes_head"];
    patch?: never;
    trace?: never;
  };
  "/api/changes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Changes
     * @description Return a feed of precomputed change events.
     */
    get: operations["list_changes_api_changes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/changes/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Change Compare
     * @description Return a precomputed diff between two snapshots.
     */
    get: operations["get_change_compare_api_changes_compare_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snapshots/{snapshot_id}/compare-live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Compare Live
     * @description Return a live diff between an archived snapshot and the current URL.
     */
    get: operations["get_compare_live_api_snapshots__snapshot_id__compare_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snapshots/{snapshot_id}/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Latest
     * @description Return the most recent snapshot for the same normalized_url_group as snapshot_id.
     */
    get: operations["get_snapshot_latest_api_snapshots__snapshot_id__latest_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snapshots/{snapshot_id}/timeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Timeline
     * @description Return a timeline of captures for the same normalized URL group.
     */
    get: operations["get_snapshot_timeline_api_snapshots__snapshot_id__timeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/changes/rss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Changes Rss
     * @description Return an RSS feed for the latest change events.
     */
    get: operations["get_changes_rss_api_changes_rss_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Lightweight liveness endpoint with optional summary checks.
     */
    get: operations["health_check_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Health Check Head
     * @description HEAD variant of the health endpoint.
     *
     *     Some external uptime monitors issue HEAD requests by default; this route
     *     mirrors the GET health check status code without returning a body.
     */
    head: operations["health_check_head_api_health_head"];
    patch?: never;
    trace?: never;
  };
  "/api/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Archive Stats
     * @description Public archive stats used by the frontend (homepage snapshot metrics).
     *
     *     Keep this lightweight and cacheable; it should not leak admin-only details.
     */
    get: operations["get_archive_stats_api_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Sources
     * @description Return per-source summary statistics derived from Snapshot data.
     */
    get: operations["list_sources_api_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_code}/editions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Source Editions
     * @description Return replayable "editions" (ArchiveJobs) for a source.
     *
     *     Each indexed ArchiveJob becomes a discrete edition in the replay service
     *     (`job-<id>` collection). The frontend uses this to power edition switching.
     */
    get: operations["list_source_editions_api_sources__source_code__editions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{source_code}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Source Preview
     * @description Return a cached preview image for a source's replay homepage.
     *
     *     These previews are generated out-of-band (e.g. via an operator script) and
     *     stored on disk under HEALTHARCHIVE_REPLAY_PREVIEW_DIR.
     */
    get: operations["get_source_preview_api_sources__source_code__preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/replay/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Resolve Replay Url
     * @description Resolve a replay URL within a specific job (pywb collection).
     *
     *     Used by the frontend edition-switching UI to determine whether the current
     *     original URL exists in another job, and if so, which capture timestamp to
     *     replay.
     */
    get: operations["resolve_replay_url_api_replay_resolve_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Snapshots
     * @description Search snapshots by keyword and/or source with simple pagination.
     */
    get: operations["search_snapshots_api_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snapshot/{snapshot_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Detail
     * @description Return metadata for a single snapshot.
     */
    get: operations["get_snapshot_detail_api_snapshot__snapshot_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snapshots/raw/{snapshot_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Raw
     * @description Serve raw HTML content for a snapshot by reading the underlying WARC record.
     */
    get: operations["get_snapshot_raw_api_snapshots_raw__snapshot_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description List archive jobs with optional filtering by source code and status.
     */
    get: operations["list_jobs_api_admin_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/jobs/status-counts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Job Status Counts
     * @description Return counts of jobs grouped by status.
     */
    get: operations["job_status_counts_api_admin_jobs_status_counts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Job Detail
     * @description Return detailed information about a single job.
     */
    get: operations["get_job_detail_api_admin_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/jobs/{job_id}/snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Job Snapshots
     * @description List snapshots associated with a given job.
     */
    get: operations["list_job_snapshots_api_admin_jobs__job_id__snapshots_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Issue Reports
     * @description List issue reports submitted via the public intake form.
     */
    get: operations["list_issue_reports_api_admin_reports_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/reports/{report_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Issue Report
     * @description Fetch a single issue report by ID.
     */
    get: operations["get_issue_report_api_admin_reports__report_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/search-debug": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Debug
     * @description Admin-only debug endpoint for search relevance.
     *
     *     Returns the same ordering as /api/search but with a score breakdown.
     */
    get: operations["search_debug_api_admin_search_debug_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ArchiveStatsSchema */
    ArchiveStatsSchema: {
      /** Snapshotstotal */
      snapshotsTotal: number;
      /** Pagestotal */
      pagesTotal: number;
      /** Sourcestotal */
      sourcesTotal: number;
      /** Latestcapturedate */
      latestCaptureDate: string | null;
      /** Latestcaptureagedays */
      latestCaptureAgeDays: number | null;
    };
    /** ChangeCompareSchema */
    ChangeCompareSchema: {
      event: components["schemas"]["ChangeEventSchema"];
      fromSnapshot: components["schemas"]["ChangeCompareSnapshotSchema"] | null;
      toSnapshot: components["schemas"]["ChangeCompareSnapshotSchema"];
      /** Diffformat */
      diffFormat: string | null;
      /** Diffhtml */
      diffHtml: string | null;
      /** Difftruncated */
      diffTruncated: boolean;
      /** Diffversion */
      diffVersion: string | null;
      /** Normalizationversion */
      normalizationVersion: string | null;
    };
    /** ChangeCompareSnapshotSchema */
    ChangeCompareSnapshotSchema: {
      /** Snapshotid */
      snapshotId: number;
      /** Title */
      title: string | null;
      /** Capturedate */
      captureDate: string;
      /** Capturetimestamp */
      captureTimestamp: string | null;
      /** Originalurl */
      originalUrl: string;
      /** Jobid */
      jobId: number | null;
      /** Jobname */
      jobName: string | null;
    };
    /** ChangeEventSchema */
    ChangeEventSchema: {
      /** Changeid */
      changeId: number;
      /** Changetype */
      changeType: string;
      /** Summary */
      summary: string | null;
      /** Highnoise */
      highNoise: boolean;
      /** Diffavailable */
      diffAvailable: boolean;
      /** Sourcecode */
      sourceCode: string | null;
      /** Sourcename */
      sourceName: string | null;
      /** Normalizedurlgroup */
      normalizedUrlGroup: string | null;
      /** Fromsnapshotid */
      fromSnapshotId: number | null;
      /** Tosnapshotid */
      toSnapshotId: number;
      /** Fromcapturetimestamp */
      fromCaptureTimestamp: string | null;
      /** Tocapturetimestamp */
      toCaptureTimestamp: string | null;
      /** Fromjobid */
      fromJobId: number | null;
      /** Tojobid */
      toJobId: number | null;
      /** Addedsections */
      addedSections: number | null;
      /** Removedsections */
      removedSections: number | null;
      /** Changedsections */
      changedSections: number | null;
      /** Addedlines */
      addedLines: number | null;
      /** Removedlines */
      removedLines: number | null;
      /** Changeratio */
      changeRatio: number | null;
    };
    /** ChangeFeedSchema */
    ChangeFeedSchema: {
      /** Enabled */
      enabled: boolean;
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Results */
      results: components["schemas"]["ChangeEventSchema"][];
    };
    /** CompareLiveDiffSchema */
    CompareLiveDiffSchema: {
      /** Diffformat */
      diffFormat: string;
      /** Diffhtml */
      diffHtml: string;
      /** Difftruncated */
      diffTruncated: boolean;
      /** Diffversion */
      diffVersion: string;
      /** Normalizationversion */
      normalizationVersion: string;
    };
    /** CompareLiveFetchSchema */
    CompareLiveFetchSchema: {
      /** Requestedurl */
      requestedUrl: string;
      /** Finalurl */
      finalUrl: string;
      /** Statuscode */
      statusCode: number;
      /** Contenttype */
      contentType: string | null;
      /** Bytesread */
      bytesRead: number;
      /**
       * Fetchedat
       * Format: date-time
       */
      fetchedAt: string;
    };
    /** CompareLiveRenderInstructionSchema */
    CompareLiveRenderInstructionSchema: {
      /** Type */
      type: string;
      /** Lineindexa */
      lineIndexA?: number | null;
      /** Lineindexb */
      lineIndexB?: number | null;
    };
    /** CompareLiveRenderSchema */
    CompareLiveRenderSchema: {
      /** Archivedlines */
      archivedLines: string[];
      /** Livelines */
      liveLines: string[];
      /** Renderinstructions */
      renderInstructions: components["schemas"]["CompareLiveRenderInstructionSchema"][];
      /** Rendertruncated */
      renderTruncated: boolean;
      /** Renderlinelimit */
      renderLineLimit: number;
    };
    /** CompareLiveSchema */
    CompareLiveSchema: {
      archivedSnapshot: components["schemas"]["ChangeCompareSnapshotSchema"];
      liveFetch: components["schemas"]["CompareLiveFetchSchema"];
      stats: components["schemas"]["CompareLiveStatsSchema"];
      diff: components["schemas"]["CompareLiveDiffSchema"];
      render: components["schemas"]["CompareLiveRenderSchema"];
      /** Textmoderequested */
      textModeRequested: string;
      /** Textmodeused */
      textModeUsed: string;
      /** Textmodefallback */
      textModeFallback: boolean;
    };
    /** CompareLiveStatsSchema */
    CompareLiveStatsSchema: {
      /** Summary */
      summary: string;
      /** Addedsections */
      addedSections: number;
      /** Removedsections */
      removedSections: number;
      /** Changedsections */
      changedSections: number;
      /** Addedlines */
      addedLines: number;
      /** Removedlines */
      removedLines: number;
      /** Changeratio */
      changeRatio: number;
      /** Highnoise */
      highNoise: boolean;
    };
    /** ExportManifestSchema */
    ExportManifestSchema: {
      /** Enabled */
      enabled: boolean;
      /** Formats */
      formats: string[];
      /** Defaultlimit */
      defaultLimit: number;
      /** Maxlimit */
      maxLimit: number;
      /** Datadictionaryurl */
      dataDictionaryUrl?: string | null;
      snapshots: components["schemas"]["ExportResourceSchema"];
      changes: components["schemas"]["ExportResourceSchema"];
    };
    /** ExportResourceSchema */
    ExportResourceSchema: {
      /** Path */
      path: string;
      /** Description */
      description: string;
      /** Formats */
      formats: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * IssueReportCategory
     * @enum {string}
     */
    IssueReportCategory:
      | "broken_snapshot"
      | "incorrect_metadata"
      | "missing_snapshot"
      | "takedown"
      | "general_feedback";
    /** IssueReportCreateSchema */
    IssueReportCreateSchema: {
      category: components["schemas"]["IssueReportCategory"];
      /** Description */
      description: string;
      /** Snapshotid */
      snapshotId?: number | null;
      /** Originalurl */
      originalUrl?: string | null;
      /** Reporteremail */
      reporterEmail?: string | null;
      /** Pageurl */
      pageUrl?: string | null;
      /** Website */
      website?: string | null;
    };
    /** IssueReportDetailSchema */
    IssueReportDetailSchema: {
      /** Id */
      id: number;
      /** Category */
      category: string;
      /** Status */
      status: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
      /** Snapshotid */
      snapshotId: number | null;
      /** Originalurl */
      originalUrl: string | null;
      /** Pageurl */
      pageUrl: string | null;
      /** Reporteremail */
      reporterEmail: string | null;
      /** Description */
      description: string;
      /** Internalnotes */
      internalNotes: string | null;
    };
    /** IssueReportListResponseSchema */
    IssueReportListResponseSchema: {
      /** Items */
      items: components["schemas"]["IssueReportSummarySchema"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** IssueReportReceiptSchema */
    IssueReportReceiptSchema: {
      /** Reportid */
      reportId: number | null;
      /** Status */
      status: string;
      /**
       * Receivedat
       * Format: date-time
       */
      receivedAt: string;
    };
    /** IssueReportSummarySchema */
    IssueReportSummarySchema: {
      /** Id */
      id: number;
      /** Category */
      category: string;
      /** Status */
      status: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Snapshotid */
      snapshotId: number | null;
      /** Originalurl */
      originalUrl: string | null;
      /** Pageurl */
      pageUrl: string | null;
    };
    /** JobDetailSchema */
    JobDetailSchema: {
      /** Id */
      id: number;
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Retrycount */
      retryCount: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Queuedat */
      queuedAt: string | null;
      /** Startedat */
      startedAt: string | null;
      /** Finishedat */
      finishedAt: string | null;
      /** Cleanupstatus */
      cleanupStatus: string;
      /** Cleanedat */
      cleanedAt: string | null;
      /** Outputdir */
      outputDir: string;
      /** Crawlerexitcode */
      crawlerExitCode: number | null;
      /** Crawlerstatus */
      crawlerStatus: string | null;
      /** Crawlerstage */
      crawlerStage: string | null;
      /** Warcfilecount */
      warcFileCount: number;
      /** Warcbytestotal */
      warcBytesTotal: number;
      /** Indexedpagecount */
      indexedPageCount: number;
      /** Pagescrawled */
      pagesCrawled: number;
      /** Pagestotal */
      pagesTotal: number;
      /** Pagesfailed */
      pagesFailed: number;
      /** Outputbytestotal */
      outputBytesTotal: number;
      /** Tmpbytestotal */
      tmpBytesTotal: number;
      /** Tmpnonwarcbytestotal */
      tmpNonWarcBytesTotal: number;
      /** Storagescannedat */
      storageScannedAt?: string | null;
      /** Finalzimpath */
      finalZimPath: string | null;
      /** Combinedlogpath */
      combinedLogPath: string | null;
      /** Statefilepath */
      stateFilePath: string | null;
      /** Config */
      config: {
        [key: string]: unknown;
      } | null;
      /** Laststats */
      lastStats: {
        [key: string]: unknown;
      } | null;
    };
    /** JobListResponseSchema */
    JobListResponseSchema: {
      /** Items */
      items: components["schemas"]["JobSummarySchema"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** JobSnapshotSummarySchema */
    JobSnapshotSummarySchema: {
      /** Id */
      id: number;
      /** Url */
      url: string;
      /**
       * Capturetimestamp
       * Format: date-time
       */
      captureTimestamp: string;
      /** Statuscode */
      statusCode: number | null;
      /** Language */
      language: string | null;
      /** Title */
      title: string | null;
    };
    /** JobStatusCountsSchema */
    JobStatusCountsSchema: {
      /** Counts */
      counts: {
        [key: string]: number;
      };
    };
    /** JobSummarySchema */
    JobSummarySchema: {
      /** Id */
      id: number;
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Retrycount */
      retryCount: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Queuedat */
      queuedAt: string | null;
      /** Startedat */
      startedAt: string | null;
      /** Finishedat */
      finishedAt: string | null;
      /** Cleanupstatus */
      cleanupStatus: string;
      /** Cleanedat */
      cleanedAt: string | null;
      /** Crawlerexitcode */
      crawlerExitCode: number | null;
      /** Crawlerstatus */
      crawlerStatus: string | null;
      /** Warcfilecount */
      warcFileCount: number;
      /** Warcbytestotal */
      warcBytesTotal: number;
      /** Indexedpagecount */
      indexedPageCount: number;
      /** Storagescannedat */
      storageScannedAt?: string | null;
    };
    /** ReplayResolveSchema */
    ReplayResolveSchema: {
      /** Found */
      found: boolean;
      /** Snapshotid */
      snapshotId?: number | null;
      /** Capturetimestamp */
      captureTimestamp?: string | null;
      /** Resolvedurl */
      resolvedUrl?: string | null;
      /** Browseurl */
      browseUrl?: string | null;
      /** Mimetype */
      mimeType?: string | null;
    };
    /** SearchDebugItemSchema */
    SearchDebugItemSchema: {
      /** Id */
      id: number;
      /** Title */
      title: string | null;
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Language */
      language: string | null;
      /**
       * Capturetimestamp
       * Format: date-time
       */
      captureTimestamp: string;
      /** Statuscode */
      statusCode: number | null;
      /** Originalurl */
      originalUrl: string;
      /** Normalizedurlgroup */
      normalizedUrlGroup: string | null;
      /** Inlinkcount */
      inlinkCount: number | null;
      /** Outlinkcount */
      outlinkCount: number | null;
      /** Pagerank */
      pagerank: number | null;
      /** Ranktext */
      rankText: number | null;
      /** Titleboost */
      titleBoost: number;
      /** Archivedpenalty */
      archivedPenalty: number;
      /** Querypenalty */
      queryPenalty: number;
      /** Trackingpenalty */
      trackingPenalty: number;
      /** Depthpenalty */
      depthPenalty: number;
      /** Authorityboost */
      authorityBoost: number;
      /** Hubnessboost */
      hubnessBoost: number;
      /** Pagerankboost */
      pagerankBoost: number;
      /** Totalscore */
      totalScore: number | null;
      /** Groupscore */
      groupScore?: number | null;
      /** Bestsnapshotid */
      bestSnapshotId?: number | null;
    };
    /** SearchDebugResponseSchema */
    SearchDebugResponseSchema: {
      /** Results */
      results: components["schemas"]["SearchDebugItemSchema"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Dialect */
      dialect: string;
      /** Mode */
      mode: string;
      /** View */
      view: string;
      /** Sort */
      sort: string;
      /** Rankingversion */
      rankingVersion: string;
      /** Querymode */
      queryMode: string | null;
      /** Usedpagesignals */
      usedPageSignals: boolean;
      /** Usedsnapshotoutlinks */
      usedSnapshotOutlinks: boolean;
      /** Usedpagerank */
      usedPagerank: boolean;
    };
    /** SearchResponseSchema */
    SearchResponseSchema: {
      /** Results */
      results: components["schemas"]["SnapshotSummarySchema"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
    };
    /**
     * SearchSort
     * @enum {string}
     */
    SearchSort: "relevance" | "newest";
    /**
     * SearchView
     * @enum {string}
     */
    SearchView: "snapshots" | "pages";
    /** SnapshotDetailSchema */
    SnapshotDetailSchema: {
      /** Id */
      id: number;
      /** Title */
      title: string | null;
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Language */
      language: string | null;
      /** Capturedate */
      captureDate: string;
      /** Capturetimestamp */
      captureTimestamp: string | null;
      /** Jobid */
      jobId: number | null;
      /** Originalurl */
      originalUrl: string;
      /** Snippet */
      snippet: string | null;
      /** Rawsnapshoturl */
      rawSnapshotUrl: string | null;
      /** Browseurl */
      browseUrl: string | null;
      /** Mimetype */
      mimeType: string | null;
      /** Statuscode */
      statusCode: number | null;
    };
    /** SnapshotLatestSchema */
    SnapshotLatestSchema: {
      /** Found */
      found: boolean;
      /** Snapshotid */
      snapshotId?: number | null;
      /** Capturetimestamp */
      captureTimestamp?: string | null;
      /** Mimetype */
      mimeType?: string | null;
    };
    /** SnapshotSummarySchema */
    SnapshotSummarySchema: {
      /** Id */
      id: number;
      /** Title */
      title: string | null;
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Language */
      language: string | null;
      /** Capturedate */
      captureDate: string;
      /** Capturetimestamp */
      captureTimestamp: string | null;
      /** Jobid */
      jobId: number | null;
      /** Originalurl */
      originalUrl: string;
      /** Snippet */
      snippet: string | null;
      /** Pagesnapshotscount */
      pageSnapshotsCount?: number | null;
      /** Rawsnapshoturl */
      rawSnapshotUrl: string | null;
      /** Browseurl */
      browseUrl: string | null;
    };
    /** SnapshotTimelineItemSchema */
    SnapshotTimelineItemSchema: {
      /** Snapshotid */
      snapshotId: number;
      /** Capturedate */
      captureDate: string;
      /** Capturetimestamp */
      captureTimestamp: string | null;
      /** Jobid */
      jobId: number | null;
      /** Jobname */
      jobName: string | null;
      /** Title */
      title: string | null;
      /** Statuscode */
      statusCode: number | null;
      /** Comparefromsnapshotid */
      compareFromSnapshotId: number | null;
      /** Browseurl */
      browseUrl?: string | null;
    };
    /** SnapshotTimelineSchema */
    SnapshotTimelineSchema: {
      /** Sourcecode */
      sourceCode: string | null;
      /** Sourcename */
      sourceName: string | null;
      /** Normalizedurlgroup */
      normalizedUrlGroup: string | null;
      /** Snapshots */
      snapshots: components["schemas"]["SnapshotTimelineItemSchema"][];
    };
    /** SourceEditionSchema */
    SourceEditionSchema: {
      /** Jobid */
      jobId: number;
      /** Jobname */
      jobName: string;
      /** Recordcount */
      recordCount: number;
      /** Firstcapture */
      firstCapture: string;
      /** Lastcapture */
      lastCapture: string;
      /** Entrybrowseurl */
      entryBrowseUrl?: string | null;
    };
    /** SourceSummarySchema */
    SourceSummarySchema: {
      /** Sourcecode */
      sourceCode: string;
      /** Sourcename */
      sourceName: string;
      /** Baseurl */
      baseUrl?: string | null;
      /** Description */
      description?: string | null;
      /** Recordcount */
      recordCount: number;
      /** Firstcapture */
      firstCapture: string;
      /** Lastcapture */
      lastCapture: string;
      /** Latestrecordid */
      latestRecordId: number | null;
      /** Entryrecordid */
      entryRecordId?: number | null;
      /** Entrybrowseurl */
      entryBrowseUrl?: string | null;
      /** Entrypreviewurl */
      entryPreviewUrl?: string | null;
    };
    /** UsageMetricsCountsSchema */
    UsageMetricsCountsSchema: {
      /** Searchrequests */
      searchRequests: number;
      /** Snapshotdetailviews */
      snapshotDetailViews: number;
      /** Rawsnapshotviews */
      rawSnapshotViews: number;
      /** Reportsubmissions */
      reportSubmissions: number;
    };
    /** UsageMetricsDaySchema */
    UsageMetricsDaySchema: {
      /** Searchrequests */
      searchRequests: number;
      /** Snapshotdetailviews */
      snapshotDetailViews: number;
      /** Rawsnapshotviews */
      rawSnapshotViews: number;
      /** Reportsubmissions */
      reportSubmissions: number;
      /** Date */
      date: string;
    };
    /** UsageMetricsSchema */
    UsageMetricsSchema: {
      /** Enabled */
      enabled: boolean;
      /** Windowdays */
      windowDays: number;
      totals: components["schemas"]["UsageMetricsCountsSchema"];
      /** Daily */
      daily: components["schemas"]["UsageMetricsDaySchema"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_issue_report_api_reports_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IssueReportCreateSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueReportReceiptSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_usage_metrics_api_usage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageMetricsSchema"];
        };
      };
    };
  };
  get_exports_manifest_api_exports_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportManifestSchema"];
        };
      };
    };
  };
  export_snapshots_api_exports_snapshots_get: {
    parameters: {
      query?: {
        format?: string;
        compressed?: boolean;
        source?: string | null;
        afterId?: number | null;
        limit?: number | null;
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_snapshots_head_api_exports_snapshots_head: {
    parameters: {
      query?: {
        format?: string;
        compressed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_changes_api_exports_changes_get: {
    parameters: {
      query?: {
        format?: string;
        compressed?: boolean;
        source?: string | null;
        afterId?: number | null;
        limit?: number | null;
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_changes_head_api_exports_changes_head: {
    parameters: {
      query?: {
        format?: string;
        compressed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_changes_api_changes_get: {
    parameters: {
      query?: {
        source?: string | null;
        jobId?: number | null;
        latest?: boolean;
        includeUnchanged?: boolean;
        from?: string | null;
        to?: string | null;
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangeFeedSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_change_compare_api_changes_compare_get: {
    parameters: {
      query: {
        toSnapshotId: number;
        fromSnapshotId?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangeCompareSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_compare_live_api_snapshots__snapshot_id__compare_live_get: {
    parameters: {
      query?: {
        mode?: string;
      };
      header?: never;
      path: {
        snapshot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompareLiveSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_latest_api_snapshots__snapshot_id__latest_get: {
    parameters: {
      query?: {
        /** @description When true (default), only return the most recent HTML snapshot for this page group. */
        requireHtml?: boolean;
      };
      header?: never;
      path: {
        snapshot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotLatestSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_timeline_api_snapshots__snapshot_id__timeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotTimelineSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_changes_rss_api_changes_rss_get: {
    parameters: {
      query?: {
        source?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_api_health_get: {
    parameters: {
      query?: {
        /** @description Include job and snapshot summary counts. */
        details?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_head_api_health_head: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_archive_stats_api_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArchiveStatsSchema"];
        };
      };
    };
  };
  list_sources_api_sources_get: {
    parameters: {
      query?: {
        lang?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceSummarySchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_source_editions_api_sources__source_code__editions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceEditionSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_preview_api_sources__source_code__preview_get: {
    parameters: {
      query: {
        jobId: number;
        lang?: string | null;
      };
      header?: never;
      path: {
        source_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_replay_url_api_replay_resolve_get: {
    parameters: {
      query: {
        jobId: number;
        url: string;
        timestamp?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReplayResolveSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_snapshots_api_search_get: {
    parameters: {
      query?: {
        q?: string | null;
        source?: string | null;
        sort?: components["schemas"]["SearchSort"] | null;
        view?: components["schemas"]["SearchView"] | null;
        includeNon2xx?: boolean;
        /** @description When view=snapshots, include same-day duplicate captures with identical content. */
        includeDuplicates?: boolean;
        /** @description Filter captures from this UTC date (YYYY-MM-DD), inclusive. */
        from?: string | null;
        /** @description Filter captures up to this UTC date (YYYY-MM-DD), inclusive. */
        to?: string | null;
        page?: number;
        pageSize?: number;
        /** @description Ranking version override (v1|v2). Default is controlled by HA_SEARCH_RANKING_VERSION. */
        ranking?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_detail_api_snapshot__snapshot_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotDetailSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_raw_api_snapshots_raw__snapshot_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_admin_jobs_get: {
    parameters: {
      query?: {
        source?: string | null;
        status?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobListResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  job_status_counts_api_admin_jobs_status_counts_get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusCountsSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_job_detail_api_admin_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path: {
        job_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetailSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_job_snapshots_api_admin_jobs__job_id__snapshots_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path: {
        job_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobSnapshotSummarySchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_issue_reports_api_admin_reports_get: {
    parameters: {
      query?: {
        status?: string | null;
        category?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueReportListResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_issue_report_api_admin_reports__report_id__get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path: {
        report_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueReportDetailSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_debug_api_admin_search_debug_get: {
    parameters: {
      query?: {
        q?: string | null;
        source?: string | null;
        sort?: components["schemas"]["SearchSort"] | null;
        view?: components["schemas"]["SearchView"] | null;
        includeNon2xx?: boolean;
        page?: number;
        pageSize?: number;
        ranking?: string | null;
      };
      header?: {
        Authorization?: string | null;
        "X-Admin-Token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchDebugResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
